export default {
  colors: {
    WHITE: "#FFFFFF",

    // BACKGROUND_PRIMARY: "#F2F2F2",
    // BACKGROUND_SECUNDARY: "#C9C9C9",
    // BACKGROUND_TERTIARY: "#D9D9D9",

    // PRIMARY: "#0367A6",
    // SECUNDARY: "4BD8F9",

    PRIMARY: "#71F79F",
    SECUNDARY: "#85F8AA",
    TERTIARY: "#97FAB4",

    BACKGROUND_PRIMARY: "#1C2326",
    BACKGROUND_SECUNDARY: "#31383A",
    BACKGROUND_TERTIARY: "#474D50",

    FONT_PRIMARY: "#253531",

    SUCCESS_PRIMARY: "#9AFECE",
    SUCCESS_TERTIARY: "#017A3F",
    SUCCESS_SECUNDARY: "#02DE74",

    ERROR_PRIMARY: "#FBE9EB",
    ERROR_TERTIARY: "#791620",
    ERROR_SECUNDARY: "#D62839",

    ALERT_PRIMARY: "#FFCE5C",
    ALERT_SECUNDARY: "#FFB60A",
    ALERT_TERTIARY: "#B88100",
  },
  typography: {
    FONT_PRIMARY: ["League Spartan", "sans-serif"].join(","),
    FONT_SECUNDARY: ["Poppins", "sans-serif"].join(","),
  },
};
